name: Sphinx Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: sulu5890/sphinx-action@4.1.2
      with:
        docs-folder: "."
